<a href="https://colab.research.google.com/github/osoliman/DSC110/blob/main/instructor_copy/10_6_2026.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Get to know the dataset

In [ ]:
#turn off AI assistance
#Documentation is the source of truth
import pandas as pd
#copy it from the repo
df = pd.read_csv('https://raw.githubusercontent.com/osoliman/DSC110/refs/heads/main/Datasets/nhanes_final.csv')

df.head()

,id,gender,age,race_ethnicity,education,bmi,height_cm,systolic_bp,has_diabetes,hba1c,fasting_glucose
0,130378.0,1.0,43.0,6.0,5.0,27.0,179.5,135.0,2.0,5.6,113.0
1,130379.0,1.0,66.0,3.0,5.0,33.5,174.2,121.0,2.0,5.6,99.0
2,130380.0,2.0,44.0,2.0,3.0,29.7,152.9,111.0,1.0,6.2,156.0
3,130381.0,2.0,5.0,7.0,NaN,23.8,120.1,NaN,2.0,NaN,NaN
4,130382.0,1.0,2.0,3.0,NaN,NaN,NaN,NaN,2.0,NaN,NaN

In [ ]:
df.head(1)

,id,gender,age,race_ethnicity,education,bmi,height_cm,systolic_bp,has_diabetes,hba1c,fasting_glucose
0,130378.0,1.0,43.0,6.0,5.0,27.0,179.5,135.0,2.0,5.6,113.0

In [ ]:
df['age'].head()

0    43.0
1    66.0
2    44.0
3     5.0
4     2.0
Name: age, dtype: float64

In [ ]:
df.tail()

,id,gender,age,race_ethnicity,education,bmi,height_cm,systolic_bp,has_diabetes,hba1c,fasting_glucose
11928,142306.0,1.0,9.0,2.0,NaN,15.4,128.0,NaN,2.0,NaN,NaN
11929,142307.0,2.0,49.0,4.0,5.0,NaN,143.8,127.0,1.0,6.2,NaN
11930,142308.0,1.0,50.0,2.0,4.0,26.4,173.3,106.0,2.0,NaN,NaN
11931,142309.0,1.0,40.0,2.0,4.0,25.5,179.1,127.0,2.0,5.2,96.0
11932,142310.0,2.0,80.0,3.0,3.0,27.6,161.7,128.0,2.0,5.3,NaN

In [ ]:
df.shape

(11933, 11)

In [ ]:
df.shape[0]

11933

In [ ]:
n_rows = df.shape[0]
n_columns = df.shape[1]
print(f'The dataset that we have contains {n_rows} rows and {n_columns} columns')

The dataset that we have contains 11933 rows and 11 columns

Data Cleaning

In [ ]:
#Python treats True as 1 and False = 0
True + True

2

In [ ]:
True + False

1

In [ ]:
1 + 1 == 3

False

In [ ]:
int(True)

1

Check for missinginess

In [ ]:
df['bmi'].isna().head()

0    False
1    False
2    False
3    False
4     True
Name: bmi, dtype: bool

In [ ]:
df.isna().sum()

id                    0
gender                0
age                   0
race_ethnicity        0
education          4139
bmi                3462
height_cm          3434
systolic_bp        4416
has_diabetes        193
hba1c              5218
fasting_glucose    8261
dtype: int64

In [ ]:
(df.isna().mean() * 100).round(1)

id                  0.0
gender              0.0
age                 0.0
race_ethnicity      0.0
education          34.7
bmi                29.0
height_cm          28.8
systolic_bp        37.0
has_diabetes        1.6
hba1c              43.7
fasting_glucose    69.2
dtype: float64

In [ ]:
df['age'].min()

5.397605346934028e-79

In [ ]:
adults = df[df['age'] > 20]

In [ ]:
(adults.isna().mean() * 100).round(1)

id                  0.0
gender              0.0
age                 0.0
race_ethnicity      0.0
education           0.2
bmi                23.5
height_cm          23.2
systolic_bp        24.9
has_diabetes        0.0
hba1c              26.1
fasting_glucose    58.9
dtype: float64

What to do with missingiess

1- Drop the missing values

In [ ]:
df_complete = df.dropna()
len(df_complete)

3075

In [ ]:
df_complete_bmi = df.dropna(subset=['bmi'])
len(df_complete_bmi)
#print before and after

8471

Fill in na with the mean

In [ ]:
df['systolic_bp'].isna().sum()

np.int64(4416)

In [ ]:
mean_sys_bp = df['systolic_bp'].mean()
print(mean_sys_bp)

119.28854596248503

In [ ]:
df['systolic_bp'] = df['systolic_bp'].fillna(mean_sys_bp)

In [ ]:
df['systolic_bp'].isna().sum()

np.int64(0)

Transform variables

In [ ]:
def bmi_check(bmi):
  if bmi < 18.5:
    bmi_result = "Underweight"
  elif bmi < 25:
    bmi_result = "Normal"
  elif bmi < 30:
    bmi_result = "Overweight"
  else:
    bmi_result = "Obese"
  return bmi_result

In [ ]:
df['bmi_category'] = df['bmi'].apply(bmi_check)

df['bmi_category'].value_counts()

bmi_category
Obese          6161
Normal         2372
Overweight     2205
Underweight    1195
Name: count, dtype: int64

In [ ]:
df['bmi_category'] = pd.cut(df['bmi'],
                            bins=[0, 18.5, 25, 30, 100],
                            labels=['Underweight', 'Normal', 'Overweight', 'Obese'])

# dropna=False also counts the missing values, so we can see them
df['bmi_category'].value_counts(dropna=False)

bmi_category
NaN            3462
Obese          2666
Normal         2400
Overweight     2189
Underweight    1216
Name: count, dtype: int64

In [ ]:
df['education'].unique()

array([ 5.,  3., nan,  2.,  4.,  1.,  9.])

In [ ]:
df['education'].head()

0    5.0
1    5.0
2    3.0
3    NaN
4    NaN
Name: education, dtype: float64

In [ ]:
# Create a mapping dictionary (adjust based on your data dictionary)
education_map = {
    1.0: 'Less than 9th grade',
    2.0: '9-11th grade',
    3.0: 'High school grad',
    4.0: 'Some college or AA degree',
    5.0: 'College graduate',
    9.0: 'Do not know',
    'None': 'Missing'
}
# Apply the mapping
df['education_label'] = df['education'].map(education_map)

In [ ]:
df['education_label'].value_counts(dropna = False)

education_label
NaN                          4139
College graduate             2625
Some college or AA degree    2370
High school grad             1749
9-11th grade                  666
Less than 9th grade           373
Do not know                    11
Name: count, dtype: int64

Data Summarization

Numerical variables

In [67]:
# Calculate mean
df['systolic_bp'].mean()

# Calculate standard deviation
df['systolic_bp'].std()

# Or get both at once
df['systolic_bp'].describe()

count    11933.000000
mean       119.288546
std         14.731242
min         61.000000
25%        112.000000
50%        119.288546
75%        121.000000
max        232.000000
Name: systolic_bp, dtype: float64

In [68]:
# Median
df['age'].median()

37.0

In [69]:
# IQR - just the 25th and 75th percentiles
df['age'].quantile([0.25, 0.75])

0.25    13.0
0.75    62.0
Name: age, dtype: float64

In [70]:
df['age'].mode()

0    80.0
Name: age, dtype: float64

Categorical variables

In [71]:
# Simple counts
df['education_label'].value_counts()

education_label
College graduate             2625
Some college or AA degree    2370
High school grad             1749
9-11th grade                  666
Less than 9th grade           373
Do not know                    11
Name: count, dtype: int64

In [72]:
# With percentages
df['education_label'].value_counts(normalize=True) * 100

education_label
College graduate             33.679754
Some college or AA degree    30.408006
High school grad             22.440339
9-11th grade                  8.545035
Less than 9th grade           4.785733
Do not know                   0.141134
Name: proportion, dtype: float64

Two categorical variables

In [73]:
# Create cross-tabulation
pd.crosstab(df['has_diabetes'], df['bmi_category'])

bmi_category  Underweight  Normal  Overweight  Obese
has_diabetes
1.0                     4     109         233    504
2.0                  1211    2251        1886   2042
3.0                     0      39          70    120
9.0                     1       1           0      0

In [74]:
# With row percentages (more useful clinically)
pd.crosstab(df['has_diabetes'], df['bmi_category'], normalize='index') * 100

bmi_category  Underweight     Normal  Overweight      Obese
has_diabetes
1.0              0.470588  12.823529   27.411765  59.294118
2.0             16.387009  30.460081   25.520974  27.631935
3.0              0.000000  17.030568   30.567686  52.401747
9.0             50.000000  50.000000    0.000000   0.000000

In [75]:
# With row percentages (more useful clinically) percentage within columns not rows
pd.crosstab(df['has_diabetes'], df['bmi_category'], normalize='columns') * 100

bmi_category  Underweight     Normal  Overweight      Obese
has_diabetes
1.0              0.328947   4.541667   10.644130  18.904726
2.0             99.588816  93.791667   86.158063  76.594149
3.0              0.000000   1.625000    3.197807   4.501125
9.0              0.082237   0.041667    0.000000   0.000000

One numeric and one categorical

In [76]:
#df.groupby('grouping_variable')['numeric_variable'].calculation()
df.groupby('has_diabetes')['bmi'].mean()

has_diabetes
1.0    32.981412
2.0    26.439797
3.0    32.068559
9.0    19.250000
Name: bmi, dtype: float64